version: 2
executorType: machine
# containerInfo:
#   - image: ubuntu:14.04
#     cmd: ["/bin/bash"]
stages:
  build:
    workDir: ~/electricitymap
    steps:
      - type: checkout
      - type: shell
        name: Show versions
        command: |
          docker --version
          docker-compose --version
      - type: shell
        name: Build
        command: |
          touch secrets.env
          docker-compose build
          docker-compose run web npm run build-release
      - type: shell
        name: Start environment
        command: |
          docker-compose up -d
          sleep 20
          docker-compose logs web
      - type: shell
        name: Run tests
        command: |
          curl --fail -i http://localhost:8000/
          curl --fail -i http://localhost:8000/health
          curl --fail -i http://localhost:8000/v1/co2?countryCode=FR
          curl --fail -i http://localhost:8000/v1/exchanges?countryCode=FR
          curl --fail -i http://localhost:8000/v1/production?countryCode=FR
          curl --fail -i http://localhost:8000/v1/price?countryCode=FR
          curl --fail -i http://localhost:8000/v2/history?countryCode=FR
          docker-compose logs web
