version: '2'
services:
  web:
    environment:
      - ENV=production
      - VIRTUAL_HOST=staging.electricitymap.org
    image: eu.gcr.io/tmrow-152415/electricitymap_web:staging
    mem_limit: 200M
    networks: [default, infrastructure] # required to be able to com' with statsd & nginx
    volumes:
      - /home/shared/electricitymap/static/dist:/home/web/public/dist

networks:
  infrastructure:
    external:
      name: infrastructure_default
