version: 2
executorType: machine
stages:
  build:
    workDir: ~/electricitymap
    steps:
      - type: checkout
      - type: shell
        name: Set Python version
        command: |
          set -eux -o pipefail
          pyenv install --list
          pyenv install 3.6.3
          pyenv global 3.6.3
      - type: shell
        name: Upgrade pip
        command: pip install -q --upgrade pip
      - type: shell
        name: Install Docker Compose
        command: pip install docker-compose==1.24.1 --progress-bar=off
      - type: shell
        name: Show versions
        command: |
          docker --version
          docker-compose --version
      - restore_cache:
          key: pip-{{ .Branch }}-{{ checksum "parsers/requirements.txt" }}
      - type: shell
        name: Lint
        command: |
          set -eux -o pipefail
          python --version
          pip -v --version
          pyenv versions
          pip install -q flake8 pylint==2.3.1 --progress-bar=off
          sudo apt-get install libxml2-dev
          pip install -q -r parsers/requirements.txt --progress-bar=off
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
          # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
          # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          pylint -E parsers/*.py -d unsubscriptable-object,unsupported-assignment-operation,unpacking-non-sequence
          python -m unittest discover parsers/test
          npm install -g jsonlint
          jsonlint -q config/*.json web/locales/*.json
      - save_cache:
          key: pip-{{ .Branch }}-{{ checksum "parsers/requirements.txt" }}
          paths:
            - "~/.cache/pip"
      - type: shell
        name: Build
        command: |
          set -euo pipefail
          docker-compose build
          # Make sure files are available outside of container
          CONTAINER_ID=$(docker create eu.gcr.io/tmrow-152415/electricitymap_web:latest)
          docker cp $CONTAINER_ID:/home/web/public/dist web/public/dist
        no_output_timeout: 30m
      - type: shell
        name: Start environment
        command: |
          set -euo pipefail
          docker-compose up -d
          sleep 20
          docker-compose logs web
      - type: shell
        name: Run tests
        command: |
          docker-compose ps
          curl --fail -i http://localhost:8000/
          curl --fail -i http://localhost:8000/v1/co2?countryCode=FR
          curl --fail -i http://localhost:8000/v1/exchanges?countryCode=FR
          curl --fail -i http://localhost:8000/v1/production?countryCode=FR
          curl --fail -i http://localhost:8000/v1/price?countryCode=FR
          curl --fail -i http://localhost:8000/v2/history?countryCode=FR
