steps:
  prepare:
    image: node:10.19.0-alpine
    inputs:
      - package.json
      - package-lock.json
    commands:
      - apk add --no-cache git imagemagick
      - npm ci
      - npm install -g cordova@9.0.0 code-push-cli@2.1.9

  build:
    inputs:
      - ../web/public/dist
      - ../web/{locales,src,views/pages/index.ejs}
      - ../web/locales-config.json
      - www/index.html
      - ./icon*.png
      - generate-index.js
      - config.xml
      - res/screen/ios
      - sentry.properties
    commands:
      - cp -r ../web/public/ www/electricitymap
      - cp -r ../web/locales/ .
      - cp ../web/locales-config.json ./locales-config.json
      - cp -r ../web/src .
      # Generate bundle
      - node generate-index.js
      # Generate icons
      - node_modules/.bin/app-icon generate -i icon_ios.png --platforms=ios
      - node_modules/.bin/app-icon generate -i icon_android_legacy.png --platforms=android --adaptive-icons
      # Set Sentry auth-token
      - echo "auth-token=${BRICK_SENTRY_AUTH_TOKEN}" >> sentry.properties
      # Build
      - touch google-services.json  # TODO: Remove
      - touch GoogleService-Info.plist  # TODO: Remove
      - cordova prepare

  deploy:
    commands:
      # Release to staging
      - code-push login --accessKey ${BRICK_CODE_PUSH_ACCESS_KEY}
      - code-push release-cordova electricitymap-android android --noDuplicateReleaseError --description ${BRICK_DRONE_COMMIT_SHA:-latest}
      - code-push release-cordova electricitymap-ios ios --noDuplicateReleaseError --description ${BRICK_DRONE_COMMIT_SHA:-latest}
      # Promote # TODO: Enable
      # - code-push promote electricitymap-android Staging Production
      # - code-push promote electricitymap-ios Staging Production
